const express = require('express');
const router = express.Router();

// Real COVID-19 data from Our World in Data (OWID)
// Dataset: https://github.com/owid/covid-19-data
// Last Updated: 2023-02-14
// Data Collection Date: February 14, 2023
const mockCountries = [
  {
    "Country": "United States",
    "country": "United States",
    "ThreeLetterSymbol": "USA",
    "iso": "USA",
    "TotalCases": 102904309,
    "cases": 102904309,
    "TotalDeaths": 1114990,
    "deaths": 1114990,
    "TotalRecovered": 101789319,
    "recovered": 101789319,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 33940,
    "todayCases": 33940,
    "NewDeaths": 445,
    "todayDeaths": 445,
    "TotalTests": 0,
    "Infection_Risk": "30.4",
    "Case_Fatality_Rate": "1.1",
    "Test_Percentage": "0",
    "Recovery_Proporation": "98.9",
    "Population": 338289856
  },
  {
    "Country": "India",
    "country": "India",
    "ThreeLetterSymbol": "IND",
    "iso": "IND",
    "TotalCases": 44685601,
    "cases": 44685601,
    "TotalDeaths": 530756,
    "deaths": 530756,
    "TotalRecovered": 44154845,
    "recovered": 44154845,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 102,
    "todayCases": 102,
    "NewDeaths": 3,
    "todayDeaths": 3,
    "TotalTests": 0,
    "Infection_Risk": "3.2",
    "Case_Fatality_Rate": "1.2",
    "Test_Percentage": "0",
    "Recovery_Proporation": "98.8",
    "Population": 1417173120
  },
  {
    "Country": "France",
    "country": "France",
    "ThreeLetterSymbol": "FRA",
    "iso": "FRA",
    "TotalCases": 39610558,
    "cases": 39610558,
    "TotalDeaths": 164691,
    "deaths": 164691,
    "TotalRecovered": 39445867,
    "recovered": 39445867,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 774,
    "critical": 774,
    "NewCases": 4986,
    "todayCases": 4986,
    "NewDeaths": 35,
    "todayDeaths": 35,
    "TotalTests": 0,
    "Infection_Risk": "58.4",
    "Case_Fatality_Rate": "0.4",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.6",
    "Population": 67813000
  },
  {
    "Country": "Germany",
    "country": "Germany",
    "ThreeLetterSymbol": "DEU",
    "iso": "DEU",
    "TotalCases": 37949446,
    "cases": 37949446,
    "TotalDeaths": 166999,
    "deaths": 166999,
    "TotalRecovered": 37782447,
    "recovered": 37782447,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 763,
    "critical": 763,
    "NewCases": 20502,
    "todayCases": 20502,
    "NewDeaths": 124,
    "todayDeaths": 124,
    "TotalTests": 0,
    "Infection_Risk": "45.5",
    "Case_Fatality_Rate": "0.4",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.6",
    "Population": 83369840
  },
  {
    "Country": "Brazil",
    "country": "Brazil",
    "ThreeLetterSymbol": "BRA",
    "iso": "BRA",
    "TotalCases": 36953492,
    "cases": 36953492,
    "TotalDeaths": 697762,
    "deaths": 697762,
    "TotalRecovered": 36255730,
    "recovered": 36255730,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "17.2",
    "Case_Fatality_Rate": "1.9",
    "Test_Percentage": "0",
    "Recovery_Proporation": "98.1",
    "Population": 215313504
  },
  {
    "Country": "Japan",
    "country": "Japan",
    "ThreeLetterSymbol": "JPN",
    "iso": "JPN",
    "TotalCases": 33012986,
    "cases": 33012986,
    "TotalDeaths": 70931,
    "deaths": 70931,
    "TotalRecovered": 32942055,
    "recovered": 32942055,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 32070,
    "todayCases": 32070,
    "NewDeaths": 135,
    "todayDeaths": 135,
    "TotalTests": 0,
    "Infection_Risk": "26.6",
    "Case_Fatality_Rate": "0.2",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.8",
    "Population": 123951696
  },
  {
    "Country": "South Korea",
    "country": "South Korea",
    "ThreeLetterSymbol": "KOR",
    "iso": "KOR",
    "TotalCases": 30384701,
    "cases": 30384701,
    "TotalDeaths": 33782,
    "deaths": 33782,
    "TotalRecovered": 30350919,
    "recovered": 30350919,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 245,
    "critical": 245,
    "NewCases": 14957,
    "todayCases": 14957,
    "NewDeaths": 24,
    "todayDeaths": 24,
    "TotalTests": 0,
    "Infection_Risk": "58.6",
    "Case_Fatality_Rate": "0.1",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.9",
    "Population": 51815808
  },
  {
    "Country": "Italy",
    "country": "Italy",
    "ThreeLetterSymbol": "ITA",
    "iso": "ITA",
    "TotalCases": 25519067,
    "cases": 25519067,
    "TotalDeaths": 187551,
    "deaths": 187551,
    "TotalRecovered": 25331516,
    "recovered": 25331516,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "43.2",
    "Case_Fatality_Rate": "0.7",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.3",
    "Population": 59037472
  },
  {
    "Country": "United Kingdom",
    "country": "United Kingdom",
    "ThreeLetterSymbol": "GBR",
    "iso": "GBR",
    "TotalCases": 24315983,
    "cases": 24315983,
    "TotalDeaths": 217705,
    "deaths": 217705,
    "TotalRecovered": 24098278,
    "recovered": 24098278,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "36.0",
    "Case_Fatality_Rate": "0.9",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.1",
    "Population": 67508936
  },
  {
    "Country": "Russia",
    "country": "Russia",
    "ThreeLetterSymbol": "RUS",
    "iso": "RUS",
    "TotalCases": 21783243,
    "cases": 21783243,
    "TotalDeaths": 387654,
    "deaths": 387654,
    "TotalRecovered": 21395589,
    "recovered": 21395589,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 9761,
    "todayCases": 9761,
    "NewDeaths": 34,
    "todayDeaths": 34,
    "TotalTests": 0,
    "Infection_Risk": "15.1",
    "Case_Fatality_Rate": "1.8",
    "Test_Percentage": "0",
    "Recovery_Proporation": "98.2",
    "Population": 144713312
  },
  {
    "Country": "Turkey",
    "country": "Turkey",
    "ThreeLetterSymbol": "TUR",
    "iso": "TUR",
    "TotalCases": 17042722,
    "cases": 17042722,
    "TotalDeaths": 101492,
    "deaths": 101492,
    "TotalRecovered": 16941230,
    "recovered": 16941230,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "20.0",
    "Case_Fatality_Rate": "0.6",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.4",
    "Population": 85341248
  },
  {
    "Country": "Spain",
    "country": "Spain",
    "ThreeLetterSymbol": "ESP",
    "iso": "ESP",
    "TotalCases": 13748918,
    "cases": 13748918,
    "TotalDeaths": 118976,
    "deaths": 118976,
    "TotalRecovered": 13629942,
    "recovered": 13629942,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "28.9",
    "Case_Fatality_Rate": "0.9",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.1",
    "Population": 47558632
  },
  {
    "Country": "Vietnam",
    "country": "Vietnam",
    "ThreeLetterSymbol": "VNM",
    "iso": "VNM",
    "TotalCases": 11526754,
    "cases": 11526754,
    "TotalDeaths": 43186,
    "deaths": 43186,
    "TotalRecovered": 11483568,
    "recovered": 11483568,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 50,
    "todayCases": 50,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "11.7",
    "Case_Fatality_Rate": "0.4",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.6",
    "Population": 98186856
  },
  {
    "Country": "Australia",
    "country": "Australia",
    "ThreeLetterSymbol": "AUS",
    "iso": "AUS",
    "TotalCases": 11330342,
    "cases": 11330342,
    "TotalDeaths": 19070,
    "deaths": 19070,
    "TotalRecovered": 11311272,
    "recovered": 11311272,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "43.3",
    "Case_Fatality_Rate": "0.2",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.8",
    "Population": 26177410
  },
  {
    "Country": "Argentina",
    "country": "Argentina",
    "ThreeLetterSymbol": "ARG",
    "iso": "ARG",
    "TotalCases": 10042136,
    "cases": 10042136,
    "TotalDeaths": 130448,
    "deaths": 130448,
    "TotalRecovered": 9911688,
    "recovered": 9911688,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "22.1",
    "Case_Fatality_Rate": "1.3",
    "Test_Percentage": "0",
    "Recovery_Proporation": "98.7",
    "Population": 45510324
  },
  {
    "Country": "Taiwan",
    "country": "Taiwan",
    "ThreeLetterSymbol": "TWN",
    "iso": "TWN",
    "TotalCases": 9842257,
    "cases": 9842257,
    "TotalDeaths": 17193,
    "deaths": 17193,
    "TotalRecovered": 9825064,
    "recovered": 9825064,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 20502,
    "todayCases": 20502,
    "NewDeaths": 36,
    "todayDeaths": 36,
    "TotalTests": 0,
    "Infection_Risk": "41.2",
    "Case_Fatality_Rate": "0.2",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.8",
    "Population": 23893396
  },
  {
    "Country": "Netherlands",
    "country": "Netherlands",
    "ThreeLetterSymbol": "NLD",
    "iso": "NLD",
    "TotalCases": 8598796,
    "cases": 8598796,
    "TotalDeaths": 23081,
    "deaths": 23081,
    "TotalRecovered": 8575715,
    "recovered": 8575715,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 15,
    "critical": 15,
    "NewCases": 1547,
    "todayCases": 1547,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "49.0",
    "Case_Fatality_Rate": "0.3",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.7",
    "Population": 17564020
  },
  {
    "Country": "Iran",
    "country": "Iran",
    "ThreeLetterSymbol": "IRN",
    "iso": "IRN",
    "TotalCases": 7565865,
    "cases": 7565865,
    "TotalDeaths": 144788,
    "deaths": 144788,
    "TotalRecovered": 7421077,
    "recovered": 7421077,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 187,
    "todayCases": 187,
    "NewDeaths": 5,
    "todayDeaths": 5,
    "TotalTests": 0,
    "Infection_Risk": "8.5",
    "Case_Fatality_Rate": "1.9",
    "Test_Percentage": "0",
    "Recovery_Proporation": "98.1",
    "Population": 88550568
  },
  {
    "Country": "Mexico",
    "country": "Mexico",
    "ThreeLetterSymbol": "MEX",
    "iso": "MEX",
    "TotalCases": 7410093,
    "cases": 7410093,
    "TotalDeaths": 332653,
    "deaths": 332653,
    "TotalRecovered": 7077440,
    "recovered": 7077440,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 9245,
    "todayCases": 9245,
    "NewDeaths": 73,
    "todayDeaths": 73,
    "TotalTests": 0,
    "Infection_Risk": "5.8",
    "Case_Fatality_Rate": "4.5",
    "Test_Percentage": "0",
    "Recovery_Proporation": "95.5",
    "Population": 127504120
  },
  {
    "Country": "Indonesia",
    "country": "Indonesia",
    "ThreeLetterSymbol": "IDN",
    "iso": "IDN",
    "TotalCases": 6733215,
    "cases": 6733215,
    "TotalDeaths": 160873,
    "deaths": 160873,
    "TotalRecovered": 6572342,
    "recovered": 6572342,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 247,
    "todayCases": 247,
    "NewDeaths": 3,
    "todayDeaths": 3,
    "TotalTests": 0,
    "Infection_Risk": "2.4",
    "Case_Fatality_Rate": "2.4",
    "Test_Percentage": "0",
    "Recovery_Proporation": "97.6",
    "Population": 275501344
  },
  {
    "Country": "Poland",
    "country": "Poland",
    "ThreeLetterSymbol": "POL",
    "iso": "POL",
    "TotalCases": 6392257,
    "cases": 6392257,
    "TotalDeaths": 118785,
    "deaths": 118785,
    "TotalRecovered": 6273472,
    "recovered": 6273472,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 2316,
    "todayCases": 2316,
    "NewDeaths": 6,
    "todayDeaths": 6,
    "TotalTests": 0,
    "Infection_Risk": "16.0",
    "Case_Fatality_Rate": "1.9",
    "Test_Percentage": "0",
    "Recovery_Proporation": "98.1",
    "Population": 39857144
  },
  {
    "Country": "Colombia",
    "country": "Colombia",
    "ThreeLetterSymbol": "COL",
    "iso": "COL",
    "TotalCases": 6355637,
    "cases": 6355637,
    "TotalDeaths": 142276,
    "deaths": 142276,
    "TotalRecovered": 6213361,
    "recovered": 6213361,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "12.3",
    "Case_Fatality_Rate": "2.2",
    "Test_Percentage": "0",
    "Recovery_Proporation": "97.8",
    "Population": 51874028
  },
  {
    "Country": "Austria",
    "country": "Austria",
    "ThreeLetterSymbol": "AUT",
    "iso": "AUT",
    "TotalCases": 5837337,
    "cases": 5837337,
    "TotalDeaths": 21795,
    "deaths": 21795,
    "TotalRecovered": 5815542,
    "recovered": 5815542,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 42,
    "critical": 42,
    "NewCases": 5218,
    "todayCases": 5218,
    "NewDeaths": 6,
    "todayDeaths": 6,
    "TotalTests": 0,
    "Infection_Risk": "65.3",
    "Case_Fatality_Rate": "0.4",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.6",
    "Population": 8939617
  },
  {
    "Country": "Ukraine",
    "country": "Ukraine",
    "ThreeLetterSymbol": "UKR",
    "iso": "UKR",
    "TotalCases": 5687118,
    "cases": 5687118,
    "TotalDeaths": 119093,
    "deaths": 119093,
    "TotalRecovered": 5568025,
    "recovered": 5568025,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 65,
    "todayCases": 65,
    "NewDeaths": 1,
    "todayDeaths": 1,
    "TotalTests": 0,
    "Infection_Risk": "14.3",
    "Case_Fatality_Rate": "2.1",
    "Test_Percentage": "0",
    "Recovery_Proporation": "97.9",
    "Population": 39701744
  },
  {
    "Country": "Portugal",
    "country": "Portugal",
    "ThreeLetterSymbol": "PRT",
    "iso": "PRT",
    "TotalCases": 5566314,
    "cases": 5566314,
    "TotalDeaths": 26103,
    "deaths": 26103,
    "TotalRecovered": 5540211,
    "recovered": 5540211,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 835,
    "todayCases": 835,
    "NewDeaths": 44,
    "todayDeaths": 44,
    "TotalTests": 0,
    "Infection_Risk": "54.2",
    "Case_Fatality_Rate": "0.5",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.5",
    "Population": 10270857
  },
  {
    "Country": "Greece",
    "country": "Greece",
    "ThreeLetterSymbol": "GRC",
    "iso": "GRC",
    "TotalCases": 5548487,
    "cases": 5548487,
    "TotalDeaths": 34779,
    "deaths": 34779,
    "TotalRecovered": 5513708,
    "recovered": 5513708,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "53.4",
    "Case_Fatality_Rate": "0.6",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.4",
    "Population": 10384972
  },
  {
    "Country": "Chile",
    "country": "Chile",
    "ThreeLetterSymbol": "CHL",
    "iso": "CHL",
    "TotalCases": 5140809,
    "cases": 5140809,
    "TotalDeaths": 64015,
    "deaths": 64015,
    "TotalRecovered": 5076794,
    "recovered": 5076794,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 1005,
    "todayCases": 1005,
    "NewDeaths": 2,
    "todayDeaths": 2,
    "TotalTests": 0,
    "Infection_Risk": "26.2",
    "Case_Fatality_Rate": "1.2",
    "Test_Percentage": "0",
    "Recovery_Proporation": "98.8",
    "Population": 19603736
  },
  {
    "Country": "Malaysia",
    "country": "Malaysia",
    "ThreeLetterSymbol": "MYS",
    "iso": "MYS",
    "TotalCases": 5039850,
    "cases": 5039850,
    "TotalDeaths": 36953,
    "deaths": 36953,
    "TotalRecovered": 5002897,
    "recovered": 5002897,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 11,
    "critical": 11,
    "NewCases": 200,
    "todayCases": 200,
    "NewDeaths": 1,
    "todayDeaths": 1,
    "TotalTests": 0,
    "Infection_Risk": "14.9",
    "Case_Fatality_Rate": "0.7",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.3",
    "Population": 33938216
  },
  {
    "Country": "Israel",
    "country": "Israel",
    "ThreeLetterSymbol": "ISR",
    "iso": "ISR",
    "TotalCases": 4792484,
    "cases": 4792484,
    "TotalDeaths": 12242,
    "deaths": 12242,
    "TotalRecovered": 4780242,
    "recovered": 4780242,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 22,
    "critical": 22,
    "NewCases": 753,
    "todayCases": 753,
    "NewDeaths": 2,
    "todayDeaths": 2,
    "TotalTests": 0,
    "Infection_Risk": "50.7",
    "Case_Fatality_Rate": "0.3",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.7",
    "Population": 9449000
  },
  {
    "Country": "Thailand",
    "country": "Thailand",
    "ThreeLetterSymbol": "THA",
    "iso": "THA",
    "TotalCases": 4727628,
    "cases": 4727628,
    "TotalDeaths": 33894,
    "deaths": 33894,
    "TotalRecovered": 4693734,
    "recovered": 4693734,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "6.6",
    "Case_Fatality_Rate": "0.7",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.3",
    "Population": 71697024
  },
  {
    "Country": "Belgium",
    "country": "Belgium",
    "ThreeLetterSymbol": "BEL",
    "iso": "BEL",
    "TotalCases": 4700949,
    "cases": 4700949,
    "TotalDeaths": 33616,
    "deaths": 33616,
    "TotalRecovered": 4667333,
    "recovered": 4667333,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "40.3",
    "Case_Fatality_Rate": "0.7",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.3",
    "Population": 11655923
  },
  {
    "Country": "Czechia",
    "country": "Czechia",
    "ThreeLetterSymbol": "CZE",
    "iso": "CZE",
    "TotalCases": 4596830,
    "cases": 4596830,
    "TotalDeaths": 42358,
    "deaths": 42358,
    "TotalRecovered": 4554472,
    "recovered": 4554472,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 1404,
    "todayCases": 1404,
    "NewDeaths": 10,
    "todayDeaths": 10,
    "TotalTests": 0,
    "Infection_Risk": "43.8",
    "Case_Fatality_Rate": "0.9",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.1",
    "Population": 10493990
  },
  {
    "Country": "Canada",
    "country": "Canada",
    "ThreeLetterSymbol": "CAN",
    "iso": "CAN",
    "TotalCases": 4582530,
    "cases": 4582530,
    "TotalDeaths": 50998,
    "deaths": 50998,
    "TotalRecovered": 4531532,
    "recovered": 4531532,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 957,
    "todayCases": 957,
    "NewDeaths": 11,
    "todayDeaths": 11,
    "TotalTests": 0,
    "Infection_Risk": "11.9",
    "Case_Fatality_Rate": "1.1",
    "Test_Percentage": "0",
    "Recovery_Proporation": "98.9",
    "Population": 38454328
  },
  {
    "Country": "Peru",
    "country": "Peru",
    "ThreeLetterSymbol": "PER",
    "iso": "PER",
    "TotalCases": 4483779,
    "cases": 4483779,
    "TotalDeaths": 219287,
    "deaths": 219287,
    "TotalRecovered": 4264492,
    "recovered": 4264492,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 50,
    "todayCases": 50,
    "NewDeaths": 18,
    "todayDeaths": 18,
    "TotalTests": 0,
    "Infection_Risk": "13.2",
    "Case_Fatality_Rate": "4.9",
    "Test_Percentage": "0",
    "Recovery_Proporation": "95.1",
    "Population": 34049588
  },
  {
    "Country": "Switzerland",
    "country": "Switzerland",
    "ThreeLetterSymbol": "CHE",
    "iso": "CHE",
    "TotalCases": 4409828,
    "cases": 4409828,
    "TotalDeaths": 14202,
    "deaths": 14202,
    "TotalRecovered": 4395626,
    "recovered": 4395626,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 995,
    "todayCases": 995,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "50.5",
    "Case_Fatality_Rate": "0.3",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.7",
    "Population": 8740471
  },
  {
    "Country": "Philippines",
    "country": "Philippines",
    "ThreeLetterSymbol": "PHL",
    "iso": "PHL",
    "TotalCases": 4074821,
    "cases": 4074821,
    "TotalDeaths": 65968,
    "deaths": 65968,
    "TotalRecovered": 4008853,
    "recovered": 4008853,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 10,
    "todayDeaths": 10,
    "TotalTests": 0,
    "Infection_Risk": "3.5",
    "Case_Fatality_Rate": "1.6",
    "Test_Percentage": "0",
    "Recovery_Proporation": "98.4",
    "Population": 115559008
  },
  {
    "Country": "South Africa",
    "country": "South Africa",
    "ThreeLetterSymbol": "ZAF",
    "iso": "ZAF",
    "TotalCases": 4059348,
    "cases": 4059348,
    "TotalDeaths": 102595,
    "deaths": 102595,
    "TotalRecovered": 3956753,
    "recovered": 3956753,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 382,
    "todayCases": 382,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "6.8",
    "Case_Fatality_Rate": "2.5",
    "Test_Percentage": "0",
    "Recovery_Proporation": "97.5",
    "Population": 59893884
  },
  {
    "Country": "Denmark",
    "country": "Denmark",
    "ThreeLetterSymbol": "DNK",
    "iso": "DNK",
    "TotalCases": 3401725,
    "cases": 3401725,
    "TotalDeaths": 8209,
    "deaths": 8209,
    "TotalRecovered": 3393516,
    "recovered": 3393516,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 155,
    "todayCases": 155,
    "NewDeaths": 3,
    "todayDeaths": 3,
    "TotalTests": 0,
    "Infection_Risk": "57.8",
    "Case_Fatality_Rate": "0.2",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.8",
    "Population": 5882259
  },
  {
    "Country": "Romania",
    "country": "Romania",
    "ThreeLetterSymbol": "ROU",
    "iso": "ROU",
    "TotalCases": 3331005,
    "cases": 3331005,
    "TotalDeaths": 67650,
    "deaths": 67650,
    "TotalRecovered": 3263355,
    "recovered": 3263355,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "16.9",
    "Case_Fatality_Rate": "2.0",
    "Test_Percentage": "0",
    "Recovery_Proporation": "98.0",
    "Population": 19659270
  },
  {
    "Country": "Hong Kong",
    "country": "Hong Kong",
    "ThreeLetterSymbol": "HKG",
    "iso": "HKG",
    "TotalCases": 2876106,
    "cases": 2876106,
    "TotalDeaths": 13333,
    "deaths": 13333,
    "TotalRecovered": 2862773,
    "recovered": 2862773,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "38.4",
    "Case_Fatality_Rate": "0.5",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.5",
    "Population": 7488863
  },
  {
    "Country": "Sweden",
    "country": "Sweden",
    "ThreeLetterSymbol": "SWE",
    "iso": "SWE",
    "TotalCases": 2696168,
    "cases": 2696168,
    "TotalDeaths": 23563,
    "deaths": 23563,
    "TotalRecovered": 2672605,
    "recovered": 2672605,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 8,
    "critical": 8,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "25.6",
    "Case_Fatality_Rate": "0.9",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.1",
    "Population": 10549349
  },
  {
    "Country": "Slovakia",
    "country": "Slovakia",
    "ThreeLetterSymbol": "SVK",
    "iso": "SVK",
    "TotalCases": 2662668,
    "cases": 2662668,
    "TotalDeaths": 20986,
    "deaths": 20986,
    "TotalRecovered": 2641682,
    "recovered": 2641682,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 315,
    "todayCases": 315,
    "NewDeaths": 4,
    "todayDeaths": 4,
    "TotalTests": 0,
    "Infection_Risk": "47.2",
    "Case_Fatality_Rate": "0.8",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.2",
    "Population": 5643455
  },
  {
    "Country": "Serbia",
    "country": "Serbia",
    "ThreeLetterSymbol": "SRB",
    "iso": "SRB",
    "TotalCases": 2481396,
    "cases": 2481396,
    "TotalDeaths": 17744,
    "deaths": 17744,
    "TotalRecovered": 2463652,
    "recovered": 2463652,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 908,
    "todayCases": 908,
    "NewDeaths": 3,
    "todayDeaths": 3,
    "TotalTests": 0,
    "Infection_Risk": "36.1",
    "Case_Fatality_Rate": "0.7",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.3",
    "Population": 6871547
  },
  {
    "Country": "Iraq",
    "country": "Iraq",
    "ThreeLetterSymbol": "IRQ",
    "iso": "IRQ",
    "TotalCases": 2465545,
    "cases": 2465545,
    "TotalDeaths": 25375,
    "deaths": 25375,
    "TotalRecovered": 2440170,
    "recovered": 2440170,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "5.5",
    "Case_Fatality_Rate": "1.0",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.0",
    "Population": 44496124
  },
  {
    "Country": "Singapore",
    "country": "Singapore",
    "ThreeLetterSymbol": "SGP",
    "iso": "SGP",
    "TotalCases": 2222006,
    "cases": 2222006,
    "TotalDeaths": 1722,
    "deaths": 1722,
    "TotalRecovered": 2220284,
    "recovered": 2220284,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "39.4",
    "Case_Fatality_Rate": "0.1",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.9",
    "Population": 5637022
  },
  {
    "Country": "New Zealand",
    "country": "New Zealand",
    "ThreeLetterSymbol": "NZL",
    "iso": "NZL",
    "TotalCases": 2200328,
    "cases": 2200328,
    "TotalDeaths": 2513,
    "deaths": 2513,
    "TotalRecovered": 2197815,
    "recovered": 2197815,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "42.4",
    "Case_Fatality_Rate": "0.1",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.9",
    "Population": 5185289
  },
  {
    "Country": "Hungary",
    "country": "Hungary",
    "ThreeLetterSymbol": "HUN",
    "iso": "HUN",
    "TotalCases": 2193272,
    "cases": 2193272,
    "TotalDeaths": 48707,
    "deaths": 48707,
    "TotalRecovered": 2144565,
    "recovered": 2144565,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "22.0",
    "Case_Fatality_Rate": "2.2",
    "Test_Percentage": "0",
    "Recovery_Proporation": "97.8",
    "Population": 9967304
  },
  {
    "Country": "Bangladesh",
    "country": "Bangladesh",
    "ThreeLetterSymbol": "BGD",
    "iso": "BGD",
    "TotalCases": 2037703,
    "cases": 2037703,
    "TotalDeaths": 29445,
    "deaths": 29445,
    "TotalRecovered": 2008258,
    "recovered": 2008258,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 15,
    "todayCases": 15,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "1.2",
    "Case_Fatality_Rate": "1.4",
    "Test_Percentage": "0",
    "Recovery_Proporation": "98.6",
    "Population": 171186368
  },
  {
    "Country": "China",
    "country": "China",
    "ThreeLetterSymbol": "CHN",
    "iso": "CHN",
    "TotalCases": 2023904,
    "cases": 2023904,
    "TotalDeaths": 87468,
    "deaths": 87468,
    "TotalRecovered": 1936436,
    "recovered": 1936436,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "0.1",
    "Case_Fatality_Rate": "4.3",
    "Test_Percentage": "0",
    "Recovery_Proporation": "95.7",
    "Population": 1425887360
  },
  {
    "Country": "Georgia",
    "country": "Georgia",
    "ThreeLetterSymbol": "GEO",
    "iso": "GEO",
    "TotalCases": 1818861,
    "cases": 1818861,
    "TotalDeaths": 16941,
    "deaths": 16941,
    "TotalRecovered": 1801920,
    "recovered": 1801920,
    "ActiveCases": 0,
    "active": 0,
    "Serious_Critical": 0,
    "critical": 0,
    "NewCases": 0,
    "todayCases": 0,
    "NewDeaths": 0,
    "todayDeaths": 0,
    "TotalTests": 0,
    "Infection_Risk": "48.6",
    "Case_Fatality_Rate": "0.9",
    "Test_Percentage": "0",
    "Recovery_Proporation": "99.1",
    "Population": 3744385
  }
];

const mockCovidData = {
  world: {
    cases: 673112695,
    deaths: 6856026,
    recovered: 666256669,
    active: 0,
    critical: 0,
    todayCases: 179088,
    todayDeaths: 1179,
    todayRecovered: 0,
    affectedCountries: 50,
    updated: Date.now(),
    dataDate: '2023-02-14'
  }
};

// Mock vaccines (archived historical data)
const mockVaccines = [
  { id: 1, name: "Pfizer-BioNTech", description: "mRNA vaccine", stage: "Approved", developer: "Pfizer/BioNTech", category: "approved" },
  { id: 2, name: "Moderna", description: "mRNA vaccine", stage: "Approved", developer: "Moderna", category: "approved" },
  { id: 3, name: "AstraZeneca", description: "Viral vector vaccine", stage: "Approved", developer: "AstraZeneca/Oxford", category: "approved" },
  { id: 4, name: "Johnson & Johnson", description: "Viral vector vaccine", stage: "Approved", developer: "Johnson & Johnson", category: "approved" },
  { id: 5, name: "Novavax", description: "Protein subunit vaccine", stage: "Approved", developer: "Novavax", category: "approved" },
  { id: 6, name: "Sinovac", description: "Inactivated virus vaccine", stage: "Approved", developer: "Sinovac", category: "approved" }
];

const mockNews = [
  { id: 1, title: "COVID-19 Data Archive (Archived)", source: "OWID", date: "2023-02-14", description: "Historical COVID-19 statistics from Our World in Data", url: "#" },
  { id: 2, title: "Vaccine Development Archive (Archived)", source: "WHO", date: new Date().toISOString(), description: "Archive of global vaccination efforts", url: "#" }
];

// NPM COVID Data endpoints (what the app actually uses)
router.get('/npm-covid-data/world', (req, res) => {
  // Return as array with capitalized field names (component expects array)
  res.json([{
    TotalCases: mockCovidData.world.cases,
    ActiveCases: mockCovidData.world.active,
    TotalDeaths: mockCovidData.world.deaths,
    NewCases: mockCovidData.world.todayCases,
    Serious_Critical: mockCovidData.world.critical,
    NewDeaths: mockCovidData.world.todayDeaths,
    TotalRecovered: mockCovidData.world.recovered
  }]);
});

router.get('/npm-covid-data/countries', (req, res) => {
  res.json(mockCountries);
});

router.get('/npm-covid-data/countries-name-ordered', (req, res) => {
  const sorted = [...mockCountries].sort((a, b) => a.Country.localeCompare(b.Country));
  res.json(sorted);
});

router.get('/npm-covid-data/countries/:continent', (req, res) => {
  res.json(mockCountries);
});

router.get('/npm-covid-data/country/:iso', (req, res) => {
  const country = mockCountries.find(c => c.iso === req.params.iso.toUpperCase() || c.ThreeLetterSymbol === req.params.iso.toUpperCase());
  if (country) {
    res.json(country);
  } else {
    res.status(404).json({ error: 'Country not found' });
  }
});

// Legacy COVID data endpoints
router.get('/covid/world', (req, res) => {
  res.json(mockCovidData.world);
});

router.get('/covid/countries', (req, res) => {
  res.json({ countries: mockCountries });
});

// Vaccine endpoints
router.get('/vaccine/all', (req, res) => {
  res.json(mockVaccines);
});

router.get('/vaccine/:id', (req, res) => {
  const vaccine = mockVaccines.find(v => v.id === parseInt(req.params.id));
  if (vaccine) {
    res.json(vaccine);
  } else {
    res.status(404).json({ error: 'Vaccine not found' });
  }
});

router.get('/vaccines/get-all-vaccines', (req, res) => {
  res.json(mockVaccines);
});

router.get('/vaccines/get-all-vaccines-pre-clinical', (req, res) => {
  res.json(mockVaccines.filter(v => v.stage === 'Pre-Clinical'));
});

router.get('/vaccines/get-all-vaccines-phase-i', (req, res) => {
  res.json(mockVaccines.filter(v => v.stage === 'Phase I'));
});

router.get('/vaccines/get-all-vaccines-phase-ii', (req, res) => {
  res.json(mockVaccines.filter(v => v.stage === 'Phase II'));
});

router.get('/vaccines/get-all-vaccines-phase-iii', (req, res) => {
  res.json(mockVaccines.filter(v => v.stage === 'Phase III'));
});

router.get('/vaccines/get-all-vaccines-phase-iv', (req, res) => {
  res.json(mockVaccines.filter(v => v.stage === 'Phase IV'));
});

router.get('/vaccines/get-fda-approved-vaccines', (req, res) => {
  res.json(mockVaccines.filter(v => v.stage === 'Approved'));
});

router.get('/vaccines/get-vaccines/:category', (req, res) => {
  res.json(mockVaccines.filter(v => v.category === req.params.category));
});

router.get('/vaccines/get-vaccines/:category/:name', (req, res) => {
  const vaccine = mockVaccines.find(v => 
    v.category === req.params.category && 
    v.name.toLowerCase().includes(req.params.name.toLowerCase())
  );
  if (vaccine) {
    res.json(vaccine);
  } else {
    res.json(mockVaccines[0]);
  }
});

// Treatment endpoints
router.get('/vaccines/get-all-treatment', (req, res) => {
  res.json([]);
});

router.get('/vaccines/get-all-treatment-pre-clinical', (req, res) => {
  res.json([]);
});

router.get('/vaccines/get-all-treatment-clinical', (req, res) => {
  res.json([]);
});

router.get('/vaccines/get-all-fda-approved-treatment', (req, res) => {
  res.json([]);
});

router.get('/vaccines/get-treatments/:category', (req, res) => {
  res.json([]);
});

// News endpoints
router.get('/news', (req, res) => {
  res.json(mockNews);
});

router.get('/news/:source', (req, res) => {
  const sourceNews = mockNews.filter(n => n.source.toLowerCase() === req.params.source.toLowerCase());
  res.json(sourceNews);
});

// Health check
router.get('/health', (req, res) => {
  res.json({ 
    status: 'Backend (Real Data API) Running', 
    timestamp: new Date().toISOString(),
    dataSource: 'Our World in Data (OWID)',
    lastUpdate: '2023-02-14'
  });
});

module.exports = router;
