export const secretData = {
  // news api
  apiKey: 'XXX',
  apiKey2: 'XXX',

  // 26 srources
  sources: [
    'abc-news',
    'abc-news-au',
    'axios',
    'bbc-news',
    'bloomberg',
    'cbc-news',
    'cbs-news',
    'cnn',
    'fox-news',
    'google-news',
    'google-news-au',
    'google-news-ca',
    'google-news-in',
    'google-news-uk',
    'medical-news-today',
    'national-geographic',
    'nbc-news',
    'news24',
    'new-scientist',
    'next-big-future',
    'the-times-of-india',
    'the-wall-street-journal',
    'the-washington-post',
    'the-washington-times',
    'time',
    'usa-today',
  ],
};
