export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const CLEAR_DATA = 'CLEAR_DATA';

export const NEWS_LOADING = 'PROFILE_LOADING';
export const GET_NEWS = 'GET_ERRORS';
export const GET_VACCINE_NEWS = 'GET_VACCINE_NEWS';
export const GET_NEXT_VACCINE_NEWS = 'GET_NEXT_VACCINE_NEWS';
export const GET_PREVIOUS_VACCINE_NEWS = 'GET_PREVIOUS_VACCINE_NEWS';
export const GET_CORONAVIRUS_NEWS = 'GET_CORONAVIRUS_NEWS';
export const GET_NEXT_CORONAVIRUS_NEWS = 'GET_NEXT_CORONAVIRUS_NEWS';
export const GET_PREVIOUS_CORONAVIRUS_NEWS = 'GET_PREVIOUS_CORONAVIRUS_NEWS';
export const GET_HEALTH_NEWS = 'GET_HEALTH_NEWS';
export const GET_NEXT_HEALTH_NEWS = 'GET_NEXT_HEALTH_NEWS';
export const GET_PREVIOUS_HEALTH_NEWS = 'GET_PREVIOUS_HEALTH_NEWS';

export const GET_WORLD_COVID_DATA = 'GET_WORLD_COVID_DATA';
export const GET_ALL_COUNTRIES_COVID_DATA = 'GET_ALL_COUNTRIES_COVID_DATA';

export const GET_ASIA_COUNTRIES_COVID_DATA = 'GET_ASIA_COUNTRIES_COVID_DATA';
export const GET_AFRICA_COUNTRIES_COVID_DATA = 'GET_AFRICA_COUNTRIES_COVID_DATA';
export const GET_EUROPE_COUNTRIES_COVID_DATA = 'GET_EUROPE_COUNTRIES_COVID_DATA';
export const GET_NORTH_AMERICA_COUNTRIES_COVID_DATA = 'GET_NORTH_AMERICA_COUNTRIES_COVID_DATA';
export const GET_SOUTH_AMERICA_COUNTRIES_COVID_DATA = 'GET_SOUTH_AMERICA_COUNTRIES_COVID_DATA';
export const GET_AUSTRALIA_OCEANIA_COUNTRIES_COVID_DATA = 'GET_AUSTRALIA_OCEANIA_COUNTRIES_COVID_DATA';

export const GET_ALL_COUNTRIES_COVID_DATA_NAME_ORDERED = 'GET_ALL_COUNTRIES_COVID_DATA_NAME_ORDERED';
export const GET_COUNTRY_ISO_BASED_DATA = 'GET_COUNTRY_ISO_BASED_DATA';
export const GET_COUNTRY_STATES_AND_CITIES_DATA = 'GET_COUNTRY_STATES_AND_CITIES_DATA';
export const GET_PROVINCE_ISO_REPORT_DATA = 'GET_PROVINCE_ISO_REPORT_DATA';
export const GET_CITIES_ISO_REPORT_DATA = 'GET_CITIES_ISO_REPORT_DATA';

export const GET_USA_STATES_DATA = 'GET_USA_STATES_DATA';
export const GET_CANADA_STATES_DATA = 'GET_CANADA_STATES_DATA';
export const GET_BRAZIL_STATES_DATA = 'GET_BRAZIL_STATES_DATA';
export const GET_GERMANY_STATES_DATA = 'GET_GERMANY_STATES_DATA';
export const GET_AUSTRALIA_STATES_DATA = 'GET_AUSTRALIA_STATES_DATA';

export const GET_OVID_DATA = 'GET_OVID_DATA';
