-- VacCOVID Database Initialization Script
-- This script initializes the PostgreSQL database for VacCOVID

-- Grant privileges to the vaccovid_user
GRANT ALL PRIVILEGES ON DATABASE vaccovid TO vaccovid_user;

-- Create extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- Create tables (simplified schema for archived data)
-- Note: Full schema should be generated by TypeORM migrations

-- Vaccine table
CREATE TABLE IF NOT EXISTS vaccine (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- News table
CREATE TABLE IF NOT EXISTS news (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  source VARCHAR(100),
  url VARCHAR(500),
  published_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_vaccine_name ON vaccine(name);
CREATE INDEX IF NOT EXISTS idx_news_published_at ON news(published_at);
CREATE INDEX IF NOT EXISTS idx_news_source ON news(source);

-- Grant permissions
GRANT SELECT ON ALL TABLES IN SCHEMA public TO vaccovid_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO vaccovid_user;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO vaccovid_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO vaccovid_user;

-- Set read-only permissions (no INSERT, UPDATE, DELETE for application user)
REVOKE INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM vaccovid_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE INSERT, UPDATE, DELETE ON TABLES FROM vaccovid_user;
