export const state_symbols = [
    // US
    { name: "Alabama", alpha2: "AL" },
    { name: "Alaska", alpha2: "AK" },
    { name: "Arizona", alpha2: "AZ" },
    { name: "Arkansas", alpha2: "AR" },
    { name: "California", alpha2: "CA" },
    { name: "Colorado", alpha2: "CO" },
    { name: "Connecticut", alpha2: "CT" },
    { name: "Delaware", alpha2: "DE" },
    { name: "District of Columbia", alpha2: "DC" },
    { name: "Florida", alpha2: "FL" },
    { name: "Georgia", alpha2: "GA" },
    { name: "Hawaii", alpha2: "HI" },
    { name: "Idaho", alpha2: "ID" },
    { name: "Illinois", alpha2: "IL" },
    { name: "Indiana", alpha2: "IN" },
    { name: "Iowa", alpha2: "IA" },
    { name: "Kansas", alpha2: "KS" },
    { name: "Kentucky", alpha2: "KY" },
    { name: "Louisiana", alpha2: "LA" },
    { name: "Maine", alpha2: "ME" },
    { name: "Maryland", alpha2: "MD" },
    { name: "Massachusetts", alpha2: "MA" },
    { name: "Michigan", alpha2: "MI" },
    { name: "Minnesota", alpha2: "MN" },
    { name: "Mississippi", alpha2: "MS" },
    { name: "Missouri", alpha2: "MO" },
    { name: "Montana", alpha2: "MT" },
    { name: "Nebraska", alpha2: "NE" },
    { name: "Nevada", alpha2: "NV" },
    { name: "New Hampshire", alpha2: "NH" },
    { name: "New Jersey", alpha2: "NJ" },
    { name: "New Mexico", alpha2: "NM" },
    { name: "New York", alpha2: "NY" },
    { name: "North Carolina", alpha2: "NC" },
    { name: "North Dakota", alpha2: "ND" },
    { name: "Ohio", alpha2: "OH" },
    { name: "Oklahoma", alpha2: "OK" },
    { name: "Oregon", alpha2: "OR" },
    { name: "Pennsylvania", alpha2: "PA" },
    { name: "Rhode Island", alpha2: "RI" },
    { name: "South Carolina", alpha2: "SC" },
    { name: "South Dakota", alpha2: "SD" },
    { name: "Tennessee", alpha2: "TN" },
    { name: "Texas", alpha2: "TX" },
    { name: "Utah", alpha2: "UT" },
    { name: "Vermont", alpha2: "VT" },
    { name: "Virginia", alpha2: "VA" },
    { name: "Washington", alpha2: "WA" },
    { name: "West Virginia", alpha2: "WV" },
    { name: "Wisconsin", alpha2: "WI" },
    { name: "Wyoming", alpha2: "WY" },
    { name: "Puerto Rico", alpha2: "PR" },
    { name: "Virgin Islands", alpha2: "VI" },
    { name: "Guam", alpha2: "GU" },
    { name: "Recovered", alpha2: "RE" },
    { name: "Diamond Princess", alpha2: "DP" },
    { name: "Grand Princess", alpha2: "GP" },
    { name: "Northern Mariana Islands", alpha2: "MP" },

    // Gerrrmany
    { name: "Baden-Wurttemberg", alpha2: "BW" },
    { name: "Bavaria", alpha2: "BV" },
    { name: "Berlin", alpha2: "BE" },
    { name: "Brandenburg", alpha2: "BB" },
    { name: "Bremen", alpha2: "HB" },
    { name: "Hamburg", alpha2: "HH" },
    { name: "Mecklenburg-Vorpommern", alpha2: "MV" },
    // { name: "Lower Saxony", alpha2: "NI" },
    { name: "Niedersachsen", alpha2: "NI" },
    { name: "Nordrhein-Westfalen", alpha2: "NW" },
    { name: "Rheinland-Pfalz", alpha2: "RP" },
    { name: "Saarland", alpha2: "SL" },
    // { name: "Saxony", alpha2: "SN" },
    { name: "Sachsen", alpha2: "SN" },
    { name: "Sachsen-Anhalt", alpha2: "ST" },
    { name: "Schleswig-Holstein", alpha2: "SH" },
    { name: "Thuringia", alpha2: "TH" },
    { name: "Thuringen", alpha2: "TH" },
    { name: "Hessen", alpha2: "HE" },
    { name: "Bayern", alpha2: "BY" },

    // Canada
    { name: "Alberta", alpha2: "AB" },
    { name: "British Columbia", alpha2: "BC" },
    // { name: "Colombie - Britannique", alpha2: "BC" },
    { name: "Manitoba", alpha2: "MB" },
    { name: "New Brunswick", alpha2: "NB" },
    { name: "Newfoundland and Labrador", alpha2: "NL" },
    { name: "Northwest Territories", alpha2: "NT" },
    // { name: "Nouveau - Brunswick", alpha2: "NB" },
    // { name: "Nouvelle - Écosse", alpha2: "NS" },
    { name: "Nova Scotia", alpha2: "NS" },
    { name: "Nunavut", alpha2: "NU" },
    { name: "Ontario", alpha2: "ON" },
    // { name: "Prince Edward Islan", alpha2: "PE" },
    { name: "Quebec", alpha2: "QC" },
    // { name: "Québec", alpha2: "QC" },
    // { name: "Saskatchewa", alpha2: "SK" },
    { name: "Saskatchewan", alpha2: "SK" },
    // { name: "Terre - Neuve - et - Labrador", alpha2: "NL" },
    // { name: "Territoires du Nord - Ouest", alpha2: "NT" },
    { name: "Yukon", alpha2: "YT" },
    { name: "Prince Edward Island", alpha2: "PE" },
    // { name: "Île - du - Prince - Édouar", alpha2: "PE" },

    // Australia
    // { name: "New South Wales", alpha2: "NSW" },
    { name: "New South Wales", alpha2: "NS" },
    // { name: "Queensland", alpha2: "QLD" },
    { name: "Queensland", alpha2: "QL" },
    { name: "South Australia", alpha2: "SA" },
    // { name: "Tasmania", alpha2: "TAS" },
    { name: "Tasmania", alpha2: "TA" },
    // { name: "Victoria", alpha2: "VIC" },
    { name: "Victoria", alpha2: "VI" },
    { name: "Western Australia", alpha2: "WA" },
    // { name: "Australian Capital Territory", alpha2: "ACT" },
    { name: "Australian Capital Territory", alpha2: "AC" },
    { name: "Northern Territory", alpha2: "NT" },

    // Brazil
    { name: "Acre", alpha2: "AC" },
    { name: "Alagoas", alpha2: "AL" },
    // { name: "Amapá", alpha2: "AP" },
    { name: "Amapa", alpha2: "AP" },
    { name: "Amazonas", alpha2: "AM" },
    { name: "Bahia", alpha2: "BA" },
    // { name: "Ceará", alpha2: "CE" },
    { name: "Ceara", alpha2: "CE" },
    // { name: "Distrito Federal	federal", alpha2: "DF" },
    { name: "Distrito Federal", alpha2: "DF" },
    // { name: "Espírito Santo", alpha2: "ES" },
    { name: "Goias", alpha2: "GO" },
    // { name: "Goiás", alpha2: "GO" },
    // { name: "Maranhão", alpha2: "MA" },
    { name: "Maranhao", alpha2: "MA" },
    { name: "Mato Grosso", alpha2: "MT" },
    { name: "Mato Grosso do Sul", alpha2: "MS" },
    { name: "Minas Gerais", alpha2: "MG" },
    // { name: "Pará", alpha2: "PA" },
    { name: "Para", alpha2: "PA" },
    // { name: "Paraíba", alpha2: "PB" },
    { name: "Paraiba", alpha2: "PB" },
    // { name: "Paraná", alpha2: "PR" },
    { name: "Parana", alpha2: "PR" },
    { name: "Pernambuco", alpha2: "PE" },
    // { name: "Piauí", alpha2: "PI" },
    { name: "Piaui", alpha2: "PI" },
    { name: "Rio de Janeiro", alpha2: "RJ" },
    { name: "Rio Grande do Norte", alpha2: "RN" },
    { name: "Rio Grande do Sul", alpha2: "RS" },
    // { name: "Rondônia", alpha2: "RO" },
    { name: "Rondonia", alpha2: "RO" },
    { name: "Roraima", alpha2: "RR" },
    { name: "Santa Catarina", alpha2: "SC" },
    // { name: "São Paulo", alpha2: "SP" },
    { name: "Sao Paulo", alpha2: "SP" },
    { name: "Sergipe", alpha2: "SE" },
    { name: "Tocantins", alpha2: "TO" },
    { name: "Espirito Santo", alpha2: "ES" },
]